import 'package:flutter/material.dart';

class CustomIconData {
  static const IconData visibility_off = IconData(0xe900, fontFamily: 'icomoon');
  static const IconData visibility_on = IconData(0xe901, fontFamily: 'icomoon');
  static const IconData cancel = IconData(0xe902, fontFamily: 'icomoon');
  static const IconData edit = IconData(0xe90d, fontFamily: 'icomoon');
  static const IconData market = IconData(0xe90f, fontFamily: 'icomoon');
  static const IconData order = IconData(0xe910, fontFamily: 'icomoon');
  static const IconData asset = IconData(0xe911, fontFamily: 'icomoon');
  static const IconData profile = IconData(0xe912, fontFamily: 'icomoon');
  static const IconData history = IconData(0xe913, fontFamily: 'icomoon');
  static const IconData keyboard_arrow_right = IconData(0xe914, fontFamily: 'icomoon');
  static const IconData withdraw = IconData(0xe915, fontFamily: 'icomoon');
  static const IconData kyc = IconData(0xe916, fontFamily: 'icomoon');
  static const IconData withdrawal_detail = IconData(0xe917, fontFamily: 'icomoon');
  static const IconData keyboard_arrow_left = IconData(0xe918, fontFamily: 'icomoon');
  static const IconData security_center = IconData(0xe919, fontFamily: 'icomoon');
  static const IconData invite_friends = IconData(0xe91a, fontFamily: 'icomoon');
  static const IconData my_team = IconData(0xe91b, fontFamily: 'icomoon');
  static const IconData announcement = IconData(0xe91c, fontFamily: 'icomoon');
  static const IconData info = IconData(0xe91d, fontFamily: 'icomoon');
  static const IconData support = IconData(0xe91e, fontFamily: 'icomoon');
  static const IconData download_center = IconData(0xe91f, fontFamily: 'icomoon');
  static const IconData no_record = IconData(0xe922, fontFamily: 'icomoon');
  static const IconData add_square = IconData(0xe923, fontFamily: 'icomoon');
  static const IconData android = IconData(0xe925, fontFamily: 'icomoon');
  static const IconData ios = IconData(0xe926, fontFamily: 'icomoon');
  static const IconData whatsapp = IconData(0xe928, fontFamily: 'icomoon');
  static const IconData telegram = IconData(0xe929, fontFamily: 'icomoon');
  static const IconData download_centre = IconData(0xe92a, fontFamily: 'icomoon');
  static const IconData camera = IconData(0xe92b, fontFamily: 'icomoon');
  static const IconData app_logo = IconData(0xe92c, fontFamily: 'icomoon');
  static const IconData info_circle = IconData(0xe92d, fontFamily: 'icomoon');
  static const IconData deposit = IconData(0xe92e, fontFamily: 'icomoon');
  static const IconData copy = IconData(0xe92f, fontFamily: 'icomoon');
  static const IconData referral_1 = IconData(0xe930, fontFamily: 'icomoon');
  static const IconData referral_2 = IconData(0xe931, fontFamily: 'icomoon');
  static const IconData referral_3 = IconData(0xe932, fontFamily: 'icomoon');
}